version: '3'
services:
  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'libray_db'
volumes:
  postgres-data:
